# Generated by Django 5.0 on 2024-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('text', 'Text'), ('integer', 'Integer'), ('image', 'Image')], default='text', max_length=100),
        ),
    ]
