# Generated by Django 5.0 on 2024-03-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('integer', 'Integer'), ('time', 'Time'), ('datetime', 'Date and Time'), ('text', 'Text'), ('date', 'Date'), ('image', 'Image')], default='text', max_length=100),
        ),
    ]
