# Generated by Django 5.0 on 2024-03-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='teacher',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('integer', 'Integer'), ('text', 'Text'), ('time', 'Time'), ('datetime', 'Date and Time'), ('image', 'Image'), ('date', 'Date')], default='text', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
