# Generated by Django 5.0 on 2024-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_teacher_options_alter_teacher_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('datetime', 'Date and Time'), ('date', 'Date'), ('image', 'Image'), ('integer', 'Integer'), ('text', 'Text'), ('time', 'Time')], default='text', max_length=100),
        ),
    ]
