# Generated by Django 5.0 on 2024-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('date', 'Date'), ('text', 'Text'), ('datetime', 'Date and Time'), ('integer', 'Integer'), ('time', 'Time')], default='text', max_length=100),
        ),
    ]
