# Generated by Django 5.0 on 2024-03-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('date', 'Date'), ('time', 'Time'), ('text', 'Text'), ('datetime', 'Date and Time'), ('integer', 'Integer')], default='text', max_length=100),
        ),
    ]
