# Generated by Django 5.0 on 2024-03-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('text', 'Text'), ('datetime', 'Date and Time'), ('time', 'Time'), ('integer', 'Integer'), ('date', 'Date'), ('image', 'Image')], default='text', max_length=100),
        ),
        migrations.AlterField(
            model_name='reportpage',
            name='page_background',
            field=models.ImageField(upload_to='mainapp/static/backgrounds/'),
        ),
    ]
