# Generated by Django 5.0 on 2024-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_reportfield_type_of_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfield',
            name='multi_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('time', 'Time'), ('text', 'Text'), ('datetime', 'Date and Time'), ('integer', 'Integer'), ('date', 'Date')], default='text', max_length=100),
        ),
    ]
