# Generated by Django 5.0 on 2024-03-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_reportfield_multi_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('date', 'Date'), ('text', 'Text'), ('datetime', 'Date and Time'), ('time', 'Time'), ('integer', 'Integer')], default='text', max_length=100),
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('choice', models.ManyToManyField(blank=True, to='mainapp.choice')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('learning_outcome', models.ManyToManyField(blank=True, related_name='section_learning_outcome', to='mainapp.learningoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentPage',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('development_goal', models.CharField(max_length=100)),
                ('key_components', models.CharField(max_length=100)),
                ('remarks', models.BooleanField(default=False)),
                ('section', models.ManyToManyField(blank=True, related_name='development_page_section', to='mainapp.section')),
            ],
        ),
    ]
