# Generated by Django 5.0 on 2024-03-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_choice_alter_reportfield_type_of_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('time', 'Time'), ('date', 'Date'), ('image', 'Image'), ('integer', 'Integer'), ('text', 'Text'), ('datetime', 'Date and Time')], default='text', max_length=100),
        ),
    ]
