# Generated by Django 5.0 on 2024-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_learningoutcome_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentpage',
            name='id',
            field=models.CharField(auto_created=True, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('time', 'Time'), ('text', 'Text'), ('datetime', 'Date and Time'), ('date', 'Date'), ('integer', 'Integer')], default='text', max_length=100),
        ),
    ]
