# Generated by Django 5.0 on 2024-03-10 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_developmentpage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('integer', 'Integer'), ('datetime', 'Date and Time'), ('time', 'Time'), ('text', 'Text'), ('date', 'Date')], default='text', max_length=100),
        ),
    ]
