# Generated by Django 5.0 on 2024-03-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_section_access_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='development_page',
            field=models.ManyToManyField(blank=True, related_name='class_development_page', to='mainapp.developmentpage'),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('datetime', 'Date and Time'), ('date', 'Date'), ('integer', 'Integer'), ('time', 'Time'), ('text', 'Text'), ('image', 'Image')], default='text', max_length=100),
        ),
    ]
