# Generated by Django 5.0 on 2024-03-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developmentpage',
            old_name='section',
            new_name='sections',
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('integer', 'Integer'), ('time', 'Time'), ('datetime', 'Date and Time'), ('image', 'Image'), ('text', 'Text'), ('date', 'Date')], default='text', max_length=100),
        ),
    ]
