# Generated by Django 5.0.3 on 2024-04-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_feedbackfieldschoice_feedbackpage_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('time', 'Time'), ('text', 'Text'), ('datetime', 'Date and Time'), ('date', 'Date'), ('image', 'Image'), ('integer', 'Integer')], default='text', max_length=100),
        ),
    ]
