# Generated by Django 5.0.3 on 2024-06-02 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_image_alter_reportfield_type_of_field_imagepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Image_page_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_image_page_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('time', 'Time'), ('integer', 'Integer'), ('image', 'Image'), ('datetime', 'Date and Time'), ('date', 'Date'), ('text', 'Text')], default='text', max_length=100),
        ),
        migrations.CreateModel(
            name='developmentPageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auth_teachers', models.ManyToManyField(blank=True, related_name='development_page_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='development_page_access',
            field=models.ManyToManyField(blank=True, related_name='development_page_access', to='mainapp.developmentpageaccess'),
        ),
    ]
