# Generated by Django 5.0.3 on 2024-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_class_image_page_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developmentpageaccess',
            old_name='Auth_teachers',
            new_name='Auth_teachers_access',
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('date', 'Date'), ('integer', 'Integer'), ('datetime', 'Date and Time'), ('text', 'Text'), ('time', 'Time'), ('image', 'Image')], default='text', max_length=100),
        ),
    ]
