# Generated by Django 5.0.3 on 2024-06-02 12:58

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_rename_auth_teachers_developmentpageaccess_auth_teachers_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='group_id',
            field=models.CharField(blank=True, default=mainapp.models.generate_unique_code, editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('time', 'Time'), ('datetime', 'Date and Time'), ('text', 'Text'), ('date', 'Date'), ('integer', 'Integer')], default='text', max_length=100),
        ),
    ]
