# Generated by Django 5.0.3 on 2024-06-02 13:01

from django.db import migrations
import random
import string

def generate_unique_code():
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=16))

def populate_group_id(apps, schema_editor):
    YourModel = apps.get_model('mainapp', 'Class')
    for obj in YourModel.objects.all():
        if not obj.group_id:
            obj.group_id = generate_unique_code()
            while YourModel.objects.filter(group_id=obj.group_id).exists():
                obj.group_id = generate_unique_code()
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_class_group_id_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.RunPython(populate_group_id),
    ]
