# Generated by Django 5.0.3 on 2024-06-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_class_group_id_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('time', 'Time'), ('datetime', 'Date and Time'), ('text', 'Text'), ('date', 'Date'), ('integer', 'Integer')], default='text', max_length=100),
        ),
    ]
