# Generated by Django 5.0.3 on 2024-06-02 13:18

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_class_name_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='group_id',
            field=models.CharField(blank=True, default=mainapp.models.generate_unique_code, editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('datetime', 'Date and Time'), ('image', 'Image'), ('text', 'Text'), ('time', 'Time'), ('date', 'Date'), ('integer', 'Integer')], default='text', max_length=100),
        ),
    ]
