# Generated by Django 5.0.3 on 2024-06-02 13:51

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_remove_class_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueGroupId',
            fields=[
                ('group_id', models.CharField(default=mainapp.models.generate_unique_code, editable=False, max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('date', 'Date'), ('image', 'Image'), ('text', 'Text'), ('integer', 'Integer'), ('time', 'Time'), ('datetime', 'Date and Time')], default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='class',
            name='group_id',
            field=models.ForeignKey(default=mainapp.models.generate_unique_group_id, editable=False, on_delete=mainapp.models.generate_unique_group_id, related_name='class_group_id', to='mainapp.uniquegroupid'),
        ),
    ]
