# Generated by Django 5.0.3 on 2024-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_uniquegroupid_alter_reportfield_type_of_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_ip', models.GenericIPAddressField(editable=False, primary_key=True, protocol='IPv6', serialize=False)),
                ('last_seen', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('integer', 'Integer'), ('date', 'Date'), ('datetime', 'Date and Time'), ('time', 'Time'), ('image', 'Image'), ('text', 'Text')], default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='uniquegroupid',
            name='group_devices',
            field=models.ManyToManyField(blank=True, related_name='group_id_online_devices', to='mainapp.device'),
        ),
    ]
