# Generated by Django 5.0.3 on 2024-06-03 04:02

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('integer', 'Integer'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('image', 'Image'), ('text', 'Text')], default='text', max_length=100),
        ),
        migrations.AlterField(
            model_name='uniquegroupid',
            name='group_id',
            field=models.CharField(default=mainapp.models.generate_unique_code, editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
