# Generated by Django 5.0.3 on 2024-06-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='commit_number',
            field=models.IntegerField(default=0, verbose_name='commit_number'),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('integer', 'Integer'), ('datetime', 'Date and Time'), ('date', 'Date'), ('text', 'Text'), ('time', 'Time')], default='text', max_length=100),
        ),
    ]
