# Generated by Django 5.0.3 on 2024-06-19 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_class_commit_number_alter_reportfield_type_of_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addmission_no', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='type_of_field',
            field=models.CharField(choices=[('image', 'Image'), ('time', 'Time'), ('text', 'Text'), ('date', 'Date'), ('datetime', 'Date and Time'), ('integer', 'Integer')], default='text', max_length=100),
        ),
        migrations.CreateModel(
            name='ClassCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.class')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.commit')),
            ],
            options={
                'unique_together': {('scheme', 'commit')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='commits',
            field=models.ManyToManyField(blank=True, related_name='class_commits', through='mainapp.ClassCommit', to='mainapp.commit'),
        ),
    ]
